baseURL = "https://cpsite.github.io/"
languageCode = "en-us"
title = "CP site Official"
theme="hugo-theme-dream"
publishDir = "docs"


enableRobotsTXT = true

hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "darkseagreen"
  #backgroundImage = "/me/background.jpg" #here is the background image
  linkColor = "seagreen"

  author = "MSA"
  avatar = "/me/f1.jpg"
  motto = "I Hate Programming. I Hate Programming. I Hate Programming. It works! I Love Programming."



  siteStartYear = 2020

  #favicon = "/favicon.ico"

  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true



email = "sabbir106706@gmail.com"
#twitter = "g1eny0ung"
facebook = "sabbir.ahmed.19101046"
instagram = "sabbir_ahmed_245"
linkedin = "sabbirahmed245"
github = "Md-Sabbir-Ahmed"
#stackoverflow = "5676489/g1eny0ung"
#codepen = "g1eny0ung"
